<% result_dir = "#{Dir.home}/cucumber-result" %>
<% Dir.mkdir result_dir unless Dir.exist? result_dir %>
<% log_dir = "#{result_dir}/logs" %>
<% Dir.mkdir log_dir unless Dir.exist? log_dir %>
<% screenshots_dir = "#{result_dir}/screenshots" %>
<% Dir.mkdir screenshots_dir unless Dir.exist? screenshots_dir %>

results_directory: <%= "#{result_dir}" %>
log_directory: <%= "#{log_dir}" %>
screenshot_directory: <%= "#{screenshots_dir}" %>

browser: firefox
base_url: https://www.google.com.sg/