login:
  username: "user@xx.com"
  password: <%= File.read("#{Dir.home}/.secure/.user_ldap").gsub("\n","") %>

browser: firefox
screenshot_directory: cucumber-result/screenshots
log_directory: cucumber-result/logs

base_url: https://www.google.com.sg/